### PR TITLE
Refactor compiler diagnostics and deprecations

### PR DESCRIPTION
**Pull request by KorigamiK**
This is my attempt to get sioyek to compile with without errors and warnings from clang.

The changes help fix deprecation warnings while compiling against Qt 6.8, compiler warnings and potential errors. 

We go from around 50+ diagnostics down to 1 so thats good. I currently didn't apply any logical changes so we should be fine. 
Please let me know about the review

### CODE REVIEW

**Comment by ahrm** [comment]
Thanks, some of these fix genuine bugs (e.g. missing \ in some regular expressions), but I don't care about most of the style warnings. For that reason I will not merge this pr but I will fix the parts where there are actual problems.

**Comment by KorigamiK** [comment]
Although I have made sure to not include any stylistic changes and only apply changes to potential bugs and deprecation updates, you are feel to apply these changes as needed.
Also I think I made some changes to `input.cpp` that were unnecessary (adding overrides), so I've fixed them in my last commit which you can check out here https://github.com/KorigamiK/sioyek/commit/7a5b030a8aedad01228ad380b3e25f03a06ca583

I can create a new pr if needed

**Comment by ahrm** [comment]
Thanks, I included most of the suggested changes in https://github.com/ahrm/sioyek/commit/ed14e38ba38da9e8eb018e09d5e02136c753929e. 

This suggestion is wrong though:
```
            if ((chars_between_last_dot_and_index[i] > 0) && (chars_between_last_dot_and_index[i] < 128) && std::isalpha(chars_between_last_dot_and_index[i])) {
            if ((chars_between_last_dot_and_index[i] > 0) && std::isalpha(chars_between_last_dot_and_index[i])) {
```

Changing the upper line to the lower line might cause a crash when dealing with non-ascii characters.

**Comment by KorigamiK** [comment]
> chars_between_last_dot_and_index[i] < 128

I think not, a signed char is always less than 128 so this is always true

**Comment by ahrm** [comment]
> I think a signed char is always less than 128 so this is always true

Not when working with unicode characters.

**Comment by KorigamiK** [comment]
> > I think a signed char is always less than 128 so this is always true
> 
> Not when working with unicode characters.

Makes sense, I think the issue might like in this container definition,
    https://github.com/ahrm/sioyek/blob/ed14e38ba38da9e8eb018e09d5e02136c753929e/pdf_viewer/utils.cpp#L544

A larger element type may be needed

**Comment by ahrm** [comment]
Yes, ideally we would use std::vector<int> in that location, but since in that function we only care about ascii characters it doesn't matter.

**Pull request closed without merging**
