### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by JingMatrix**
These commits will use system-wise libraries for `mupdf`, `sqlite3` and `utf8`.
I tested it on my Ubuntu machine, not able to test for windows.

### CODE REVIEW

**Comment by JingMatrix** [comment]
I removed git-submodules, so the above build release won't pass.
Please tell on Windows or Mac to see if it works @ahrm .

**Comment by JingMatrix** [comment]
Or you can keep this pull-request open, (or you can create a new branch), to simplify building process for linux users.

**Comment by ahrm** [comment]
I am hesitant to accept changes that modify dependencies because getting them working in multiple operating systems was a nightmare.

**Comment by JingMatrix** [comment]
If I guess correctly, most dependencies problem comes from Windows instead of Mac, is that right?
Personally, I would suggest using CMake buiding system to improve this problem.

**Comment by ahrm** [comment]
Actually windows was quite easy. The main problem is various linux distributions and minor package difference between them.

**Comment by JingMatrix** [comment]
Could you give some expamles for your comments on various linux distributions? For exmaple, are there some related issues in the list?
Because I am really not convinced of this.

**Comment by ahrm** [comment]
For example ubuntu 18.04 LTS has an outdated version of `mupdf` that doesn't work with sioyek so we have to compile mupdf from source but then sometimes the `libharfbuzz` package from the system clashes with the `libharfbuzz` in mupdf source code and causes a hard crash, but if we don't install `libharfbuzz` there are problems for users who want to use their system's mupdf (there are multiple github issues about that). Most distributions don't need to explicitly install `gumbo-parser` because it is included in the mupdf package but some do. The name of some packages are different in different distributions, etc. etc.

I am hesitant to accept changes that change dependencies unless you explicitly test in on following systems:
* Windows 10+
* MacOS latest version
* Ubuntu 18.04 LTS and 22.04 LTS
* Archlinux

But your change for column handling in `synctex` is good, why don't you make a pull request without changing the dependencies?

**Comment by JingMatrix** [comment]
Well, my personal opinion is that we should use `CMake` build system to explicitly require the dependencies versions.
Providing (common) dependencies, such as `mupdf`, is the task of users instead of maintainers.
Usually, I believed that we need a sub-module only when we have a modified fork for our purpose.
This is just my personal ideas from experience, you may think differently.
For long-term maintenance, I strongly recommand so.

I am on Ubuntu 22.10, and it passed the compilation and works smoothly.
I don't use Windows 10, no way for me to test it.

With a copy of synctex in the repo for me is not a good idea.
 I made this pull-request because the old version of synctex isn't working on my computer. So I turned to the latest version.

I will cherry pick the synctex and send a pull-request for it.

**Pull request closed without merging**
