### PR TITLE
Synctex update

### PR DESCRIPTION
**Pull request by JingMatrix**
This commits updates `synctex` to 1.21, from https://github.com/jlaurens/synctex.

### CODE REVIEW

**Comment by ahrm** [comment]
Doesn't compile on my machine with visual studio 2022. The problem seems to be these lines:
```
__attribute__((__format__ (__printf__, 1, 2)))
```
which seem to be a gcc-specific extension. It can be fixed by defining it out:
```
#define attribute(x)
```
then it needs `shlwapi.lib` as an additional link dependency to work. These solutions are too hacky so I prefer to just using the old version of synctex. What exactly is your issue with the included version of synctex? Does it not work on your machine?

**Comment by JingMatrix** [comment]
I think it is safe to define `__attribute__(x)` or just remove thoes lines, as suggested in https://stackoverflow.com/a/18690636/7870953 .

> then it needs `shlwapi.lib` as an additional link dependency to work. 

This is related to the lines
https://github.com/jlaurens/synctex/blob/2020/synctex_parser_utils.c#L66-L69 .
And people have asked related questions in https://stackoverflow.com/questions/38167618/how-can-i-use-the-c-shlwapi-library-in-visual-studio, so I guess that one only needs to add a line
```
#pragma comment(lib, "shlwapi.lib")
```
after those lines as answered there, this is in the official docs: https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathfindnextcomponenta .

> These solutions are too hacky so I prefer to just using the old version of synctex. 

These are maybe the somehow `mistakes` of  the author of `synctex`, he might just hadn't enough considerations for 
possible new versions of `msvc` in 2020.
I think it is easier for you to verify these corrections since I don't have a `msvc` disponible, I will add a new commit for it.
But I am really curious, why the github building process succeed while yours failed?

> What exactly is your issue with the included version of synctex? Does it not work on your machine?

When I invoked it, it shows blank screen and some `SynxTex Error` info, this is even the case when I used the pre-built AppImage. There wasn't error in my supplied arguments since they work perfectly with latest version.

**Comment by JingMatrix** [comment]
Could you please try to compile and test it again? @ahrm .
I believe that they are not hacky.

**Comment by ahrm** [comment]
First of all there was still some `__attribute__`s that had to be undefined. But even then it doesn't work on windows. The scanner object is null in both forward and backward searches in the following lines:
https://github.com/ahrm/sioyek/blob/a90813cef9322aa8fb5ea70a0fbefdc75773994a/pdf_viewer/main_widget.cpp#L689
https://github.com/ahrm/sioyek/blob/a90813cef9322aa8fb5ea70a0fbefdc75773994a/pdf_viewer/main_widget.cpp#L1100

**Comment by JingMatrix** [comment]
Where are thoes remained `__attribute__`?  I did a `grep` and  there are only 5 of them in total. Are there any caching mechinism?

Currently I have no idea about the null scanner.

**Comment by ahrm** [comment]
I fixed it in this commit in `synctex_update` branch. There were two issues:
* `add_quotes` which was supposed to be a boolean had a value of -1
* The updated `_synctex_strip_last_path_extension` for windows breaks `sioyek` because we already converted paths to be compatible with older versions of synctex, so I just commented the windows specific code out.

Any way, this version of synctex seems to not really be stable and there seems to be a lot of bugs. I will merge this into main when synctex is more stable, or maybe you could make it work with an older and more stable version of synctex? `1.17` perhaps?

**Comment by JingMatrix** [comment]
The version `1.21` is released in `2020`, and is currenly used everywhere I believed, it should be stable as part of the Latex suite.
On linux, we don't need to complie it, just install `libsynctex-dev` and everything runs smoothly. That is why originally I created the reduce-dependencies pull-request.
I am not on windows, so I could not know the difficulty you might experience.

As for chosing anothoer version, it is really not needed for linux systems since using system-wise lib is much better.
If your workaround works well and you are confident about it, I think it is Okay to merge into the main.
I am wondering if I should change `#ifdefn` to `#if defined`, it might be the problem why you saw remained `__attribute__`.
Could you test this conjecture? I will send a commit to change them.

**Comment by ahrm** [comment]
merged in e258755b2508a0f5efac7e482b4d24db4fddff29.

**Comment by JingMatrix** [comment]
Please add a line 
```c
#pragma comment(lib, "shlwapi.lib")
```
after the line
https://github.com/ahrm/sioyek/blob/e258755b2508a0f5efac7e482b4d24db4fddff29/pdf_viewer/synctex/synctex_parser_utils.c#L68 

Otherwise, others might have linking problem.
I guess you might have compiled it correctly since you configured through Visual Studio to add it as linking dependency.
But this could be an issue for others, so it is better to make it as a macro for `msvc`.

**Comment by ahrm** [comment]
I commented out the lines which use this library so it shouldn't be a problem.

**Comment by JingMatrix** [comment]
Ok, I see it.

**Pull request closed without merging**
