### PR TITLE
add ctrl-n/p to move selection

### PR DESCRIPTION
**Pull request by KorigamiK**

### CODE REVIEW

**Comment by ahrm** [comment]
You can already do this by adding this to your `keys_user.config`:
```
[m]control_menu('down') <C-n>
[m]control_menu('up') <C-p>
```

**Comment by KorigamiK** [comment]
Ah, didn't know about that. Is this already documented?

**Comment by ahrm** [comment]
No, the new features in the development branch are not documented yet.

**Comment by KorigamiK** [comment]
> No, the new features in the development branch are not documented yet.

Got it. I'll be closing this then.

**Pull request closed without merging**
