### PR TITLE
Make sudo make install work again

### PR DESCRIPTION
**Pull request by raffaem**

### CODE REVIEW

**Comment by ahrm** [comment]
Please make sure this doesn't break AppImage builds built using this: https://github.com/ahrm/sioyek/blob/main/.github/workflows/build_and_release.yml .

**Comment by raffaem** [comment]
> Please make sure this doesn't break AppImage builds built using this: https://github.com/ahrm/sioyek/blob/main/.github/workflows/build_and_release.yml .

Sorry I have no experience with AppImage.

**Comment by raffaem** [comment]
> Please make sure this doesn't break AppImage builds built using this: https://github.com/ahrm/sioyek/blob/main/.github/workflows/build_and_release.yml .

Building the AppImage works, but I have switched from [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) to [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) due to [this](https://github.com/probonopd/linuxdeployqt/issues/340)

**Comment by ahrm** [comment]
> but I have switched from [linuxdeployqt](https://github.com/probonopd/linuxdeployqt)

Don't do that. We initially used `linuxdeploy` but had to switch to `linuxdeployqt` because it had some issues.
Also don't remove `LINUX_STANDARD_PATH`, there is a reason it is there.

**Comment by raffaem** [comment]
> We initially used linuxdeploy but had to switch to linuxdeployqt because it had some issues.

Well I can't test the AppImage with linuxdeployqt due to the issue I linked

> We initially used linuxdeploy but had to switch to linuxdeployqt because it had some issues.

Can I ask what it is?

**Comment by ahrm** [comment]
> Can I ask what it is?

Some packages use that option (in fact, the reason we introduced that option was to help linux packagers).

**Comment by raffaem** [comment]
May I ask what are the problems with linuxdeploy?

Because the [issue with linuxdeployqt](https://github.com/probonopd/linuxdeployqt/issues/340) cannot be overcome. There is no switch to deactivate the "feature".

How are you running linuxdeployqt?

What distribution do you have?

**Comment by ahrm** [comment]
> May I ask what are the problems with linuxdeploy?

I don't remember what it was, but it was a serious issue because I also had the same problem you are having with `linuxdeployqt` and had to install an Ubuntu 18.04 virtual machine to get it working, yet I still chose to do it instead of using `linuxdeploy`.

I think `linuxdeploy` didn't correctly bundle some of the qt-specific libraries with the application. 

Anyway, all builds are using the `Ubuntu 18.04` github actions machine.

**Comment by raffaem** [comment]
All right, here is the code with `linuxdeploy` for further reference.

I wonder how the packages are going to fare now that `LINUX_STANDARD_PATH` is always set?

```
#!/usr/bin/env bash

if [ -z ${MAKE_PARALLEL+x} ]; then export MAKE_PARALLEL=1; else echo "MAKE_PARALLEL defined"; fi
echo "MAKE_PARALLEL set to $MAKE_PARALLEL"

# download linuxdeploy if it does not exists
if [[ ! -f ./linuxdeploy-x86_64.AppImage ]]; then

	wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
	chmod +x ./linuxdeploy-x86_64.AppImage
fi

# download linuxdeploy-plugin-qt if it does not exists
if [[ ! -f ./linuxdeploy-plugin-qt-x86_64.AppImage ]]; then
	wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
	chmod +x ./linuxdeploy-plugin-qt-x86_64.AppImage
fi

cd mupdf
make USE_SYSTEM_HARFBUZZ=yes
cd ..

if [[ $1 == portable ]]; then
	qmake-qt5 "CONFIG+=linux_app_image" pdf_viewer_build_config.pro
else
	qmake-qt5 "CONFIG+=linux_app_image non_portable" pdf_viewer_build_config.pro
fi

rm -r sioyek-release 2> /dev/null
make install INSTALL_ROOT=sioyek-release -j$MAKE_PARALLEL

if [[ $1 == portable ]]; then
	cp pdf_viewer/prefs.config sioyek-release/usr/bin/prefs.config
	cp pdf_viewer/prefs_user.config sioyek-release/usr/bin/prefs_user.config
	cp pdf_viewer/keys.config sioyek-release/usr/bin/keys.config
	cp pdf_viewer/keys_user.config sioyek-release/usr/bin/keys_user.config
	cp -r pdf_viewer/shaders sioyek-release/usr/bin/shaders
	cp tutorial.pdf sioyek-release/usr/bin/tutorial.pdf
else
	cp pdf_viewer/prefs.config sioyek-release/usr/bin/prefs.config
	cp pdf_viewer/prefs_user.config sioyek-release/usr/share/prefs_user.config
	cp pdf_viewer/keys.config sioyek-release/usr/bin/keys.config
	cp pdf_viewer/keys_user.config sioyek-release/usr/share/keys_user.config
	cp -r pdf_viewer/shaders sioyek-release/usr/bin/shaders
	cp tutorial.pdf sioyek-release/usr/bin/tutorial.pdf
fi

./linuxdeploy-x86_64.AppImage --desktop-file ./sioyek-release/usr/share/applications/sioyek.desktop --plugin qt --appdir sioyek-release --output appimage

if [[ $1 == portable ]]; then
	rm -r Sioyek-x86_64.AppImage.config
	rm Sioyek-x86_64.AppImage
	mv Sioyek-* Sioyek-x86_64.AppImage
	mkdir -p Sioyek-x86_64.AppImage.config/.local/share/Sioyek
	cp tutorial.pdf Sioyek-x86_64.AppImage.config/.local/share/Sioyek/tutorial.pdf
	zip -r sioyek-release-linux-portable.zip Sioyek-x86_64.AppImage.config Sioyek-x86_64.AppImage
else
	mv Sioyek-* Sioyek-x86_64.AppImage
	zip sioyek-release-linux.zip Sioyek-x86_64.AppImage
fi

```

**Pull request merged**
